### ISSUE TITLE
Compile Error? on Mac OSX 10.15.7

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_tensorflow#42]
I tried running this command to compile from the source. 

```
python3 --version
>>Python 3.8.5

Command used: 
python3 build_ovtf.py --use_prebuilt_tensorflow

Package             Version
------------------- -------
Keras               2.4.3
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.2
mock                4.0.3
numpy               1.18.5
pip                 21.0.1
psutil              5.8.0
setuptools          54.1.2
six                 1.15.0
termcolor           1.1.0
wheel               0.36.2
yapf                0.26.0
Target Arch: native
Using TensorFlow version v2.2.2
Install TensorFlow
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
ERROR: Could not find a version that satisfies the requirement tensorflow-custom-abi0
ERROR: No matching distribution found for tensorflow-custom-abi0
Traceback (most recent call last):
  File "build_ovtf.py", line 501, in <module>
    main()
  File "build_ovtf.py", line 281, in main
    command_executor(
  File "/Users/rlo/Documents/openvino_dev/openvino_tensorflow/tools/build_utils.py", line 62, in command_executor
    assert retcode == 0, "dir:" + os.getcwd(
AssertionError: dir:/Users/rlo/Documents/openvino_dev/openvino_tensorflow/build_cmake. Error in running command: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tensorflow-custom-abi0


```

**Comment by suryasidd** [comment]
This product does not support MacOS in this release. We have it in our roadmap and plan to support in future releases. Please take a look at the following table for all the supported configurations. https://openvinotoolkit.github.io/openvino_tensorflow/
